AllCops:
  Exclude:
    - vendor/**/*
    - test/**/*
    - bin/**/*
    - files/default/plugins/*
    - files/default/extensions/*
    - files/default/handlers/*
    - files/default/transports/*

# other configuration
# ...

Documentation:
  Enabled: false

AlignParameters:
  Enabled: false

Metrics/LineLength:
  Max: 400

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 50

