language: ruby
dist: xenial
sudo: required
bundler_args: --without integration
rvm:
  - 2.4.1
env:
  - KITCHEN=default-ubuntu-1404
#  - KITCHEN=default-ubuntu-1604
#  - KITCHEN=default-centos-7x
  - KITCHEN=server-redis-ubuntu-1404
#  - KITCHEN=server-redis-ubuntu-1604
#  - KITCHEN=server-redis-centos-7x
  - KITCHEN=client-ubuntu-1404
#  - KITCHEN=client-ubuntu-1604
#  - KITCHEN=client-centos-7x
  - KITCHEN=client-redis-ubuntu-1404
#  - KITCHEN=client-redis-ubuntu-1604
#  - KITCHEN=client-redis-centos-7x
before_install:
  - sudo apt-get -qq update
  - gem install bundler
  - travis_retry wget -c https://packages.chef.io/files/stable/chefdk/2.3.4/ubuntu/16.04/chefdk_2.3.4-1_amd64.deb
  - sudo dpkg -i chefdk_2.3.4-1_amd64.deb
  - travis_retry wget -c https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb
  - sudo dpkg -i vagrant_2.0.1_x86_64.deb
  - sudo apt-get install -y lxc
  - sudo apt-get install -y lxctl
  - vagrant plugin install vagrant-lxc
  - sudo vagrant lxc sudoers
  - vagrant plugin install aws
script:
  - cat /etc/os-release
  - bundle install
  - bundle exec foodcritic .
  - bundle exec rubocop .
  - /opt/chefdk/bin/kitchen test $KITCHEN
